include classpath("application.conf")

node-address {
  protocol = http
  host = "elasticmq"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
}

queues {
  "limnopulse-notification-jobs-dlq" {
    defaultVisibilityTimeout = 60 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
  }

  "limnopulse-notification-jobs" {
    defaultVisibilityTimeout = 60 seconds
    delay = 0 seconds
    receiveMessageWait = 20 seconds
    deadLettersQueue {
      name = "limnopulse-notification-jobs-dlq"
      maxReceiveCount = 8
    }
  }

  "limnopulse-telegram-notification-jobs-dlq" {
    defaultVisibilityTimeout = 60 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
  }

  "limnopulse-telegram-notification-jobs" {
    defaultVisibilityTimeout = 60 seconds
    delay = 0 seconds
    receiveMessageWait = 20 seconds
    deadLettersQueue {
      name = "limnopulse-telegram-notification-jobs-dlq"
      maxReceiveCount = 8
    }
  }

  "limnopulse-ses-events-dlq" {
    defaultVisibilityTimeout = 60 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
  }

  "limnopulse-ses-events" {
    defaultVisibilityTimeout = 60 seconds
    delay = 0 seconds
    receiveMessageWait = 20 seconds
    deadLettersQueue {
      name = "limnopulse-ses-events-dlq"
      maxReceiveCount = 8
    }
  }

  "limnopulse-ses-events-routing-dlq" {
    defaultVisibilityTimeout = 60 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
  }
}
